# Indicates compatibility version with lifecycle
api = "0.8"

[buildpack]
description = "A Cloud Native Buildpack that installs scarb"
homepage = "https://github.com/amp-buildpacks/scarb"
id = "amp-buildpacks/starknet-foundry"
keywords = ["cairo", "starknet-foundry"]
name = "AMP Buildpack for Starknet-foundry"
sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
version = "{{.version}}"

[[buildpack.licenses]]
type = "Apache-2.0"
uri = "https://github.com/amp-buildpacks/starknet-foundry/blob/main/LICENSE"

[metadata]
include-files = ["LICENSE", "README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
pre-package = "scripts/build.sh"

[[metadata.configurations]]
build = true
default = "false"
description = "enable the sncast deploy contract"
name = "BP_ENABLE_DEPLOY_PROCESS"

[[metadata.configurations]]
build = true
default = "0.17.1"
description = "the starknet foundry version"
name = "BP_STARKNET_FOUNDRY_VERSION"

[[metadata.configurations]]
build = true
default = "gnu"
description = "libc implementation: gnu or musl"
name = "BP_STARKNET_FOUNDRY_LIBC"

[[metadata.dependencies]]
id = "starknet-foundry-musl"
name = "Starknet Foundry (musl libc)"
purl = "pkg:generic/starknet-foundry@0.17.1"
stacks = ["*"]
uri = "https://github.com/foundry-rs/starknet-foundry/releases/download/v0.17.1/starknet-foundry-v0.17.1-x86_64-unknown-linux-musl.tar.gz"
version = "0.17.1"

[[metadata.dependencies]]
id = "starknet-foundry-gnu"
name = "Starknet Foundry (gnu libc)"
purl = "pkg:generic/scarb@0.17.1"
stacks = ["*"]
uri = "https://github.com/foundry-rs/starknet-foundry/releases/download/v0.17.1/starknet-foundry-v0.17.1-x86_64-unknown-linux-gnu.tar.gz"
version = "0.17.1"

[[metadata.dependencies.licenses]]
type = "MIT"
uri = "https://github.com/software-mansion/scarb/blob/main/LICENSE"

[[stacks]]
id = "*"
